### PR TITLE
Remove git depedency

### PR DESCRIPTION
**Pull request by bouk**
Apply code formatting
Add Gemfile.lock to gitignore
Add npm-debug.log to gitignore
Remove -l from bash

@phutchins cleaned up the project a bit and removed the git dependency, as that is used for git version management, not the git resource (which is built into chef)

### CODE REVIEW

**Comment by phutchins** [comment]
@bouk, much appreciated. Great changes. Merged.

After a few other merges, tests aren't running from a fresh environment. Working on those now...

**Comment by phutchins** [comment]
Actually, @bouk looking at this, how did you plan on having git installed? The git chef resource still relies on git being installed on the system. Tests are now failing.

Also, why did you remove the -l flag from bash?

**Comment by bouk** [comment]
@phutchins the git resource doesn't deal with that https://docs.chef.io/resource_git.html. The cookbooks that I'm using it installs git in a different way, and it was conflicting with the git cookbook. We could still use that cookbook in the tests I guess?

I removed `-l` because it didn't work for me otherwise, not sure why

**Comment by phutchins** [comment]
@bouk I'd like the cookbook to work without a wrapper as it has before which requires git to be installed on the system. We could add a conditional around the include_recipe for git so that you could disable it if you like. It would be enabled by default however. Also to do this cleanly, we should expose the option to the resource which may change the way that we include the cookbook as we probably shouldn't be including a cookbook in a lwrp. Open to other ideas if you have them.

The -l creates a login shell in bash. Historically this was the only way for me to get the shell in the correct scope. I left it out and tests appear to pass so it's possible that something was changed (fixed) in core chef to make this not necessary.

**Comment by bouk** [comment]
I'm unsure what the best way is to resolve the git dependency, because there's so many ways to install it.

We could also just run the install script https://github.com/creationix/nvm/blob/master/install.sh or download nvm.sh via https and create the directory ourselves. I'm more leaning towards the latter.

**Comment by phutchins** [comment]
@bouk I don't see a reason to get rid of git as a dependency from my use case. Even the install.sh script uses git. It has the option to download the source from github via raw which would be the way to go if we had a good reason to make removing git optional. I may not be considering a case where installing git might be difficult or cumbersome so I'm definitely open to entertaining the idea.

If you'd like to take a stab at implementing grabbing the raw content (like here: https://github.com/creationix/nvm/blob/master/install.sh#L32) using raw from github without calling the install.sh script, I would be glad to work with you to get it merged.

**Pull request merged**
